Doc move to github for Instagram Authenticator
wso2-extensions/identity-outbound-auth-instagram pull request #5
Opened 2019-01-17 11:37 UTC by nalakas

Doc move to github for Instagram Authenticator

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2019-01-29 08:02 UTC, menakaj requested changes

2019-01-29 08:02 UTC, menakaj commented on docs/README.md
> +* If you want to upgrade the Github Authenticator (.jar) in your existing IS pack, follow the bellow instructions.
Github authenticator? or Instagram?

2019-01-29 08:02 UTC, menakaj commented on docs/README.md
> +  * Download and extract the latest version of the connector artifacts (.jar, .war, gadgets etc.,) from the connector store.
connector artifacts === authenticator artifacts.

2019-01-29 08:02 UTC, menakaj commented on docs/README.md
> +  * Replace the old .jar file found in the <IS_HOME>/repository/components/dropins folder with the new .jar file that you downloaded.
Mention the name of the .jar file. we can use wildcards for version. i.e org.wso2.carbon.extension.identity.authenticator.outbound.instagram-x.x.jar

2019-01-29 08:02 UTC, menakaj commented on docs/README.md
> +    |Field|Description|SAmple value|
Typo... should be: Sample Value

2019-01-29 08:52 UTC, nalakas commented on docs/README.md
> +* If you want to upgrade the Github Authenticator (.jar) in your existing IS pack, follow the bellow instructions.
fixed

2019-01-29 08:52 UTC, nalakas commented on docs/README.md
> +  * Download and extract the latest version of the connector artifacts (.jar, .war, gadgets etc.,) from the connector store.
fixed

2019-01-29 08:52 UTC, nalakas commented on docs/README.md
> +  * Replace the old .jar file found in the <IS_HOME>/repository/components/dropins folder with the new .jar file that you downloaded.
fixed

2019-01-29 08:52 UTC, nalakas commented on docs/README.md
> +    |Field|Description|SAmple value|
fixed

2019-07-05 06:36 UTC, menakaj approved these changes

2019-07-05 06:37 UTC, merged